module Highlighter
  module Utils
    class Prism
      class << self
        Language = Struct.new(:name, :js_url)

        def prismjs
          'https://cdn.jsdelivr.net/prism/1.3.0/prism.js'
        end

        def themes
          {
            coy: 'https://cdn.jsdelivr.net/prism/1.3.0/themes/prism-coy.css',
            dark: 'https://cdn.jsdelivr.net/prism/1.3.0/themes/prism-dark.css',
            funky: 'https://cdn.jsdelivr.net/prism/1.3.0/themes/prism-funky.css',
            okaidia: 'https://cdn.jsdelivr.net/prism/1.3.0/themes/prism-okaidia.css',
            tomorrow: 'https://cdn.jsdelivr.net/prism/1.3.0/themes/prism-tomorrow.css',
            twilight: 'https://cdn.jsdelivr.net/prism/1.3.0/themes/prism-twilight.css',
            default: 'https://cdn.jsdelivr.net/prism/1.3.0/themes/prism.css',
          }
        end

        def languages
          {
            'ABAP' => Language.new('abap', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-abap.min.js'),
            'abap' => Language.new('abap', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-abap.min.js'),
            'ActionScript' => Language.new('actionscript', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-actionscript.min.js'),
            'actionscript' => Language.new('actionscript', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-actionscript.min.js'),
            'actionscript3' => Language.new('actionscript', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-actionscript.min.js'),
            'as3' => Language.new('actionscript', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-actionscript.min.js'),
            'ApacheConf' => Language.new('apacheconf', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-apacheconf.min.js'),
            'apacheconf' => Language.new('apacheconf', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-apacheconf.min.js'),
            'aconf' => Language.new('apacheconf', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-apacheconf.min.js'),
            'apache' => Language.new('apacheconf', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-apacheconf.min.js'),
            'APL' => Language.new('apl', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-apl.min.js'),
            'apl' => Language.new('apl', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-apl.min.js'),
            'AppleScript' => Language.new('applescript', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-applescript.min.js'),
            'applescript' => Language.new('applescript', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-applescript.min.js'),
            'osascript' => Language.new('applescript', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-applescript.min.js'),
            'AsciiDoc' => Language.new('asciidoc', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-asciidoc.min.js'),
            'asciidoc' => Language.new('asciidoc', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-asciidoc.min.js'),
            'AutoHotkey' => Language.new('autohotkey', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-autohotkey.min.js'),
            'autohotkey' => Language.new('autohotkey', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-autohotkey.min.js'),
            'ahk' => Language.new('autohotkey', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-autohotkey.min.js'),
            'AutoIt' => Language.new('autoit', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-autoit.min.js'),
            'autoit' => Language.new('autoit', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-autoit.min.js'),
            'au3' => Language.new('autoit', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-autoit.min.js'),
            'AutoIt3' => Language.new('autoit', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-autoit.min.js'),
            'AutoItScript' => Language.new('autoit', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-autoit.min.js'),
            'Shell' => Language.new('bash', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-bash.min.js'),
            'shell' => Language.new('bash', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-bash.min.js'),
            'sh' => Language.new('bash', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-bash.min.js'),
            'bash' => Language.new('bash', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-bash.min.js'),
            'zsh' => Language.new('bash', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-bash.min.js'),
            'Batchfile' => Language.new('batch', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-batch.min.js'),
            'batchfile' => Language.new('batch', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-batch.min.js'),
            'bat' => Language.new('batch', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-batch.min.js'),
            'batch' => Language.new('batch', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-batch.min.js'),
            'dosbatch' => Language.new('batch', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-batch.min.js'),
            'winbatch' => Language.new('batch', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-batch.min.js'),
            'Bison' => Language.new('bison', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-bison.min.js'),
            'bison' => Language.new('bison', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-bison.min.js'),
            'Brainfuck' => Language.new('brainfuck', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-brainfuck.min.js'),
            'brainfuck' => Language.new('brainfuck', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-brainfuck.min.js'),
            'C' => Language.new('c', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-c.min.js'),
            'c' => Language.new('c', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-c.min.js'),
            'CoffeeScript' => Language.new('coffeescript', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-coffeescript.min.js'),
            'coffeescript' => Language.new('coffeescript', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-coffeescript.min.js'),
            'coffee' => Language.new('coffeescript', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-coffeescript.min.js'),
            'coffee-script' => Language.new('coffeescript', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-coffeescript.min.js'),
            'C++' => Language.new('cpp', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-cpp.min.js'),
            'c++' => Language.new('cpp', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-cpp.min.js'),
            'cpp' => Language.new('cpp', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-cpp.min.js'),
            'Crystal' => Language.new('crystal', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-crystal.min.js'),
            'crystal' => Language.new('crystal', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-crystal.min.js'),
            'C#' => Language.new('csharp', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-csharp.min.js'),
            'c#' => Language.new('csharp', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-csharp.min.js'),
            'csharp' => Language.new('csharp', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-csharp.min.js'),
            'CSS' => Language.new('css', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-css.min.js'),
            'css' => Language.new('css', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-css.min.js'),
            'D' => Language.new('d', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-d.min.js'),
            'd' => Language.new('d', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-d.min.js'),
            'Dart' => Language.new('dart', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-dart.min.js'),
            'dart' => Language.new('dart', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-dart.min.js'),
            'Diff' => Language.new('diff', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-diff.min.js'),
            'diff' => Language.new('diff', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-diff.min.js'),
            'udiff' => Language.new('diff', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-diff.min.js'),
            'Eiffel' => Language.new('eiffel', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-eiffel.min.js'),
            'eiffel' => Language.new('eiffel', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-eiffel.min.js'),
            'Elixir' => Language.new('elixir', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-elixir.min.js'),
            'elixir' => Language.new('elixir', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-elixir.min.js'),
            'Erlang' => Language.new('erlang', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-erlang.min.js'),
            'erlang' => Language.new('erlang', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-erlang.min.js'),
            'FORTRAN' => Language.new('fortran', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-fortran.min.js'),
            'fortran' => Language.new('fortran', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-fortran.min.js'),
            'F#' => Language.new('fsharp', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-fsharp.min.js'),
            'f#' => Language.new('fsharp', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-fsharp.min.js'),
            'fsharp' => Language.new('fsharp', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-fsharp.min.js'),
            'Cucumber' => Language.new('gherkin', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-gherkin.min.js'),
            'cucumber' => Language.new('gherkin', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-gherkin.min.js'),
            'gherkin' => Language.new('gherkin', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-gherkin.min.js'),
            'GLSL' => Language.new('glsl', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-glsl.min.js'),
            'glsl' => Language.new('glsl', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-glsl.min.js'),
            'Go' => Language.new('go', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-go.min.js'),
            'go' => Language.new('go', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-go.min.js'),
            'Groovy' => Language.new('groovy', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-groovy.min.js'),
            'groovy' => Language.new('groovy', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-groovy.min.js'),
            'Haml' => Language.new('haml', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-haml.min.js'),
            'haml' => Language.new('haml', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-haml.min.js'),
            'Handlebars' => Language.new('handlebars', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-handlebars.min.js'),
            'handlebars' => Language.new('handlebars', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-handlebars.min.js'),
            'hbs' => Language.new('handlebars', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-handlebars.min.js'),
            'htmlbars' => Language.new('handlebars', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-handlebars.min.js'),
            'Haskell' => Language.new('haskell', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-haskell.min.js'),
            'haskell' => Language.new('haskell', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-haskell.min.js'),
            'Haxe' => Language.new('haxe', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-haxe.min.js'),
            'haxe' => Language.new('haxe', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-haxe.min.js'),
            'HTTP' => Language.new('http', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-http.min.js'),
            'http' => Language.new('http', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-http.min.js'),
            'i7' => Language.new('inform7', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-inform7.min.js'),
            'inform7' => Language.new('inform7', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-inform7.min.js'),
            'INI' => Language.new('ini', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-ini.min.js'),
            'ini' => Language.new('ini', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-ini.min.js'),
            'dosini' => Language.new('ini', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-ini.min.js'),
            'J' => Language.new('j', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-j.min.js'),
            'j' => Language.new('j', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-j.min.js'),
            'Jade' => Language.new('jade', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-jade.min.js'),
            'jade' => Language.new('jade', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-jade.min.js'),
            'Java' => Language.new('java', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-java.min.js'),
            'java' => Language.new('java', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-java.min.js'),
            'JavaScript' => Language.new('javascript', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-javascript.min.js'),
            'javascript' => Language.new('javascript', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-javascript.min.js'),
            'js' => Language.new('javascript', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-javascript.min.js'),
            'node' => Language.new('javascript', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-javascript.min.js'),
            'JSX' => Language.new('jsx', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-jsx.min.js'),
            'jsx' => Language.new('jsx', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-jsx.min.js'),
            'Julia' => Language.new('julia', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-julia.min.js'),
            'julia' => Language.new('julia', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-julia.min.js'),
            'Kotlin' => Language.new('kotlin', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-kotlin.min.js'),
            'kotlin' => Language.new('kotlin', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-kotlin.min.js'),
            'TeX' => Language.new('latex', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-latex.min.js'),
            'tex' => Language.new('latex', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-latex.min.js'),
            'latex' => Language.new('latex', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-latex.min.js'),
            'Less' => Language.new('less', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-less.min.js'),
            'less' => Language.new('less', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-less.min.js'),
            'LOLCODE' => Language.new('lolcode', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-lolcode.min.js'),
            'lolcode' => Language.new('lolcode', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-lolcode.min.js'),
            'Lua' => Language.new('lua', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-lua.min.js'),
            'lua' => Language.new('lua', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-lua.min.js'),
            'Makefile' => Language.new('makefile', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-makefile.min.js'),
            'makefile' => Language.new('makefile', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-makefile.min.js'),
            'bsdmake' => Language.new('makefile', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-makefile.min.js'),
            'make' => Language.new('makefile', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-makefile.min.js'),
            'mf' => Language.new('makefile', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-makefile.min.js'),
            'Markdown' => Language.new('markdown', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-markdown.min.js'),
            'markdown' => Language.new('markdown', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-markdown.min.js'),
            'Matlab' => Language.new('matlab', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-matlab.min.js'),
            'matlab' => Language.new('matlab', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-matlab.min.js'),
            'octave' => Language.new('matlab', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-matlab.min.js'),
            'Monkey' => Language.new('monkey', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-monkey.min.js'),
            'monkey' => Language.new('monkey', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-monkey.min.js'),
            'Assembly' => Language.new('nasm', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-nasm.min.js'),
            'assembly' => Language.new('nasm', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-nasm.min.js'),
            'nasm' => Language.new('nasm', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-nasm.min.js'),
            'Nginx' => Language.new('nginx', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-nginx.min.js'),
            'nginx' => Language.new('nginx', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-nginx.min.js'),
            'Nix' => Language.new('nix', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-nix.min.js'),
            'nix' => Language.new('nix', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-nix.min.js'),
            'nixos' => Language.new('nix', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-nix.min.js'),
            'NSIS' => Language.new('nsis', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-nsis.min.js'),
            'nsis' => Language.new('nsis', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-nsis.min.js'),
            'Objective-C' => Language.new('objectivec', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-objectivec.min.js'),
            'objective-c' => Language.new('objectivec', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-objectivec.min.js'),
            'obj-c' => Language.new('objectivec', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-objectivec.min.js'),
            'objc' => Language.new('objectivec', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-objectivec.min.js'),
            'objectivec' => Language.new('objectivec', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-objectivec.min.js'),
            'OCaml' => Language.new('ocaml', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-ocaml.min.js'),
            'ocaml' => Language.new('ocaml', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-ocaml.min.js'),
            'Oz' => Language.new('oz', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-oz.min.js'),
            'oz' => Language.new('oz', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-oz.min.js'),
            'Pascal' => Language.new('pascal', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-pascal.min.js'),
            'pascal' => Language.new('pascal', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-pascal.min.js'),
            'Perl' => Language.new('perl', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-perl.min.js'),
            'perl' => Language.new('perl', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-perl.min.js'),
            'PHP' => Language.new('php', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-php.min.js'),
            'php' => Language.new('php', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-php.min.js'),
            'inc' => Language.new('php', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-php.min.js'),
            'PowerShell' => Language.new('powershell', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-powershell.min.js'),
            'powershell' => Language.new('powershell', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-powershell.min.js'),
            'posh' => Language.new('powershell', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-powershell.min.js'),
            'Processing' => Language.new('processing', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-processing.min.js'),
            'processing' => Language.new('processing', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-processing.min.js'),
            'Prolog' => Language.new('prolog', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-prolog.min.js'),
            'prolog' => Language.new('prolog', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-prolog.min.js'),
            'Puppet' => Language.new('puppet', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-puppet.min.js'),
            'puppet' => Language.new('puppet', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-puppet.min.js'),
            'Python' => Language.new('python', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-python.min.js'),
            'python' => Language.new('python', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-python.min.js'),
            'rusthon' => Language.new('python', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-python.min.js'),
            'R' => Language.new('r', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-r.min.js'),
            'r' => Language.new('r', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-r.min.js'),
            'Rscript' => Language.new('r', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-r.min.js'),
            'splus' => Language.new('r', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-r.min.js'),
            'Ruby' => Language.new('ruby', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-ruby.min.js'),
            'ruby' => Language.new('ruby', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-ruby.min.js'),
            'jruby' => Language.new('ruby', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-ruby.min.js'),
            'macruby' => Language.new('ruby', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-ruby.min.js'),
            'rake' => Language.new('ruby', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-ruby.min.js'),
            'rb' => Language.new('ruby', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-ruby.min.js'),
            'rbx' => Language.new('ruby', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-ruby.min.js'),
            'Rust' => Language.new('rust', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-rust.min.js'),
            'rust' => Language.new('rust', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-rust.min.js'),
            'SAS' => Language.new('sas', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-sas.min.js'),
            'sas' => Language.new('sas', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-sas.min.js'),
            'Sass' => Language.new('sass', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-sass.min.js'),
            'sass' => Language.new('sass', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-sass.min.js'),
            'Scala' => Language.new('scala', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-scala.min.js'),
            'scala' => Language.new('scala', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-scala.min.js'),
            'Scheme' => Language.new('scheme', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-scheme.min.js'),
            'scheme' => Language.new('scheme', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-scheme.min.js'),
            'SCSS' => Language.new('scss', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-scss.min.js'),
            'scss' => Language.new('scss', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-scss.min.js'),
            'Smalltalk' => Language.new('smalltalk', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-smalltalk.min.js'),
            'smalltalk' => Language.new('smalltalk', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-smalltalk.min.js'),
            'squeak' => Language.new('smalltalk', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-smalltalk.min.js'),
            'Smarty' => Language.new('smarty', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-smarty.min.js'),
            'smarty' => Language.new('smarty', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-smarty.min.js'),
            'SQL' => Language.new('sql', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-sql.min.js'),
            'sql' => Language.new('sql', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-sql.min.js'),
            'Stylus' => Language.new('stylus', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-stylus.min.js'),
            'stylus' => Language.new('stylus', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-stylus.min.js'),
            'Swift' => Language.new('swift', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-swift.min.js'),
            'swift' => Language.new('swift', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-swift.min.js'),
            'Tcl' => Language.new('tcl', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-tcl.min.js'),
            'tcl' => Language.new('tcl', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-tcl.min.js'),
            'Textile' => Language.new('textile', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-textile.min.js'),
            'textile' => Language.new('textile', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-textile.min.js'),
            'Twig' => Language.new('twig', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-twig.min.js'),
            'twig' => Language.new('twig', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-twig.min.js'),
            'TypeScript' => Language.new('typescript', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-typescript.min.js'),
            'typescript' => Language.new('typescript', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-typescript.min.js'),
            'ts' => Language.new('typescript', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-typescript.min.js'),
            'Verilog' => Language.new('verilog', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-verilog.min.js'),
            'verilog' => Language.new('verilog', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-verilog.min.js'),
            'VHDL' => Language.new('vhdl', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-vhdl.min.js'),
            'vhdl' => Language.new('vhdl', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-vhdl.min.js'),
            'VimL' => Language.new('vim', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-vim.min.js'),
            'viml' => Language.new('vim', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-vim.min.js'),
            'vim' => Language.new('vim', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-vim.min.js'),
            'nvim' => Language.new('vim', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-vim.min.js'),
            'YAML' => Language.new('yaml', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-yaml.min.js'),
            'yaml' => Language.new('yaml', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-yaml.min.js'),
            'yml' => Language.new('yaml', 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-yaml.min.js'),
          }
        end

        def plugins
          {
            autolinker: 'https://cdn.jsdelivr.net/prism/1.3.0/plugins/autolinker/prism-autolinker.min.js',
            autoloader: 'https://cdn.jsdelivr.net/prism/1.3.0/plugins/autoloader/prism-autoloader.min.js',
            file_highlight: 'https://cdn.jsdelivr.net/prism/1.3.0/plugins/file-highlight/prism-file-highlight.min.js',
            highlight_keywords: 'https://cdn.jsdelivr.net/prism/1.3.0/plugins/highlight-keywords/prism-highlight-keywords.min.js',
            ie8: 'https://cdn.jsdelivr.net/prism/1.3.0/plugins/ie8/prism-ie8.min.js',
            jsonp_highlight: 'https://cdn.jsdelivr.net/prism/1.3.0/plugins/jsonp-highlight/prism-jsonp-highlight.min.js',
            keep_markup: 'https://cdn.jsdelivr.net/prism/1.3.0/plugins/keep-markup/prism-keep-markup.min.js',
            line_highlight: 'https://cdn.jsdelivr.net/prism/1.3.0/plugins/line-highlight/prism-line-highlight.min.js',
            line_numbers: 'https://cdn.jsdelivr.net/prism/1.3.0/plugins/line-numbers/prism-line-numbers.min.js',
            previewer_angle: 'https://cdn.jsdelivr.net/prism/1.3.0/plugins/previewer-angle/prism-previewer-angle.min.js',
            previewer_base: 'https://cdn.jsdelivr.net/prism/1.3.0/plugins/previewer-base/prism-previewer-base.min.js',
            previewer_color: 'https://cdn.jsdelivr.net/prism/1.3.0/plugins/previewer-color/prism-previewer-color.min.js',
            previewer_easing: 'https://cdn.jsdelivr.net/prism/1.3.0/plugins/previewer-easing/prism-previewer-easing.min.js',
            previewer_gradient: 'https://cdn.jsdelivr.net/prism/1.3.0/plugins/previewer-gradient/prism-previewer-gradient.min.js',
            previewer_time: 'https://cdn.jsdelivr.net/prism/1.3.0/plugins/previewer-time/prism-previewer-time.min.js',
            remove_initial_line_feed: 'https://cdn.jsdelivr.net/prism/1.3.0/plugins/remove-initial-line-feed/prism-remove-initial-line-feed.min.js',
            show_invisibles: 'https://cdn.jsdelivr.net/prism/1.3.0/plugins/show-invisibles/prism-show-invisibles.min.js',
            show_language: 'https://cdn.jsdelivr.net/prism/1.3.0/plugins/show-language/prism-show-language.min.js',
            wpd: 'https://cdn.jsdelivr.net/prism/1.3.0/plugins/wpd/prism-wpd.min.js',
          }
        end
      end
    end
  end
end
