module Highlighter
  module Utils
    class Prism
      class << self
        def prismjs
          'https://cdn.jsdelivr.net/prism/1.3.0/prism.js'
        end

        def themes
          {
            coy: 'https://cdn.jsdelivr.net/prism/1.3.0/themes/prism-coy.css',
            dark: 'https://cdn.jsdelivr.net/prism/1.3.0/themes/prism-dark.css',
            funky: 'https://cdn.jsdelivr.net/prism/1.3.0/themes/prism-funky.css',
            okaidia: 'https://cdn.jsdelivr.net/prism/1.3.0/themes/prism-okaidia.css',
            tomorrow: 'https://cdn.jsdelivr.net/prism/1.3.0/themes/prism-tomorrow.css',
            twilight: 'https://cdn.jsdelivr.net/prism/1.3.0/themes/prism-twilight.css',
            default: 'https://cdn.jsdelivr.net/prism/1.3.0/themes/prism.css',
          }
        end

        def languages
          {
            'ABAP' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-abap.min.js',
            'abap' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-abap.min.js',
            'ActionScript' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-actionscript.min.js',
            'actionscript' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-actionscript.min.js',
            'actionscript 3' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-actionscript.min.js',
            'actionscript3' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-actionscript.min.js',
            'as3' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-actionscript.min.js',
            'ApacheConf' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-apacheconf.min.js',
            'apacheconf' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-apacheconf.min.js',
            'aconf' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-apacheconf.min.js',
            'apache' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-apacheconf.min.js',
            'APL' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-apl.min.js',
            'apl' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-apl.min.js',
            'AppleScript' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-applescript.min.js',
            'applescript' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-applescript.min.js',
            'osascript' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-applescript.min.js',
            'AsciiDoc' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-asciidoc.min.js',
            'asciidoc' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-asciidoc.min.js',
            'AutoHotkey' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-autohotkey.min.js',
            'autohotkey' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-autohotkey.min.js',
            'ahk' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-autohotkey.min.js',
            'AutoIt' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-autoit.min.js',
            'autoit' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-autoit.min.js',
            'au3' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-autoit.min.js',
            'AutoIt3' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-autoit.min.js',
            'AutoItScript' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-autoit.min.js',
            'Shell' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-bash.min.js',
            'shell' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-bash.min.js',
            'sh' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-bash.min.js',
            'bash' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-bash.min.js',
            'zsh' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-bash.min.js',
            'Batchfile' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-batch.min.js',
            'batchfile' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-batch.min.js',
            'bat' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-batch.min.js',
            'batch' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-batch.min.js',
            'dosbatch' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-batch.min.js',
            'winbatch' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-batch.min.js',
            'Bison' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-bison.min.js',
            'bison' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-bison.min.js',
            'Brainfuck' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-brainfuck.min.js',
            'brainfuck' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-brainfuck.min.js',
            'C' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-c.min.js',
            'c' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-c.min.js',
            'CoffeeScript' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-coffeescript.min.js',
            'coffeescript' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-coffeescript.min.js',
            'coffee' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-coffeescript.min.js',
            'coffee-script' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-coffeescript.min.js',
            'C++' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-cpp.min.js',
            'c++' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-cpp.min.js',
            'cpp' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-cpp.min.js',
            'Crystal' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-crystal.min.js',
            'crystal' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-crystal.min.js',
            'C#' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-csharp.min.js',
            'c#' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-csharp.min.js',
            'csharp' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-csharp.min.js',
            'CSS' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-css.min.js',
            'css' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-css.min.js',
            'D' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-d.min.js',
            'd' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-d.min.js',
            'Dart' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-dart.min.js',
            'dart' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-dart.min.js',
            'Diff' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-diff.min.js',
            'diff' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-diff.min.js',
            'udiff' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-diff.min.js',
            'Eiffel' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-eiffel.min.js',
            'eiffel' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-eiffel.min.js',
            'Elixir' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-elixir.min.js',
            'elixir' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-elixir.min.js',
            'Erlang' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-erlang.min.js',
            'erlang' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-erlang.min.js',
            'FORTRAN' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-fortran.min.js',
            'fortran' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-fortran.min.js',
            'F#' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-fsharp.min.js',
            'f#' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-fsharp.min.js',
            'fsharp' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-fsharp.min.js',
            'Cucumber' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-gherkin.min.js',
            'cucumber' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-gherkin.min.js',
            'gherkin' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-gherkin.min.js',
            'GLSL' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-glsl.min.js',
            'glsl' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-glsl.min.js',
            'Go' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-go.min.js',
            'go' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-go.min.js',
            'Groovy' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-groovy.min.js',
            'groovy' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-groovy.min.js',
            'Haml' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-haml.min.js',
            'haml' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-haml.min.js',
            'Handlebars' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-handlebars.min.js',
            'handlebars' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-handlebars.min.js',
            'hbs' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-handlebars.min.js',
            'htmlbars' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-handlebars.min.js',
            'Haskell' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-haskell.min.js',
            'haskell' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-haskell.min.js',
            'Haxe' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-haxe.min.js',
            'haxe' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-haxe.min.js',
            'HTTP' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-http.min.js',
            'http' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-http.min.js',
            'Inform 7' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-inform7.min.js',
            'inform 7' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-inform7.min.js',
            'i7' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-inform7.min.js',
            'inform7' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-inform7.min.js',
            'INI' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-ini.min.js',
            'ini' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-ini.min.js',
            'dosini' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-ini.min.js',
            'J' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-j.min.js',
            'j' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-j.min.js',
            'Jade' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-jade.min.js',
            'jade' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-jade.min.js',
            'Java' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-java.min.js',
            'java' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-java.min.js',
            'JavaScript' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-javascript.min.js',
            'javascript' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-javascript.min.js',
            'js' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-javascript.min.js',
            'node' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-javascript.min.js',
            'JSX' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-jsx.min.js',
            'jsx' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-jsx.min.js',
            'Julia' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-julia.min.js',
            'julia' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-julia.min.js',
            'Kotlin' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-kotlin.min.js',
            'kotlin' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-kotlin.min.js',
            'TeX' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-latex.min.js',
            'tex' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-latex.min.js',
            'latex' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-latex.min.js',
            'Less' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-less.min.js',
            'less' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-less.min.js',
            'LOLCODE' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-lolcode.min.js',
            'lolcode' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-lolcode.min.js',
            'Lua' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-lua.min.js',
            'lua' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-lua.min.js',
            'Makefile' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-makefile.min.js',
            'makefile' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-makefile.min.js',
            'bsdmake' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-makefile.min.js',
            'make' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-makefile.min.js',
            'mf' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-makefile.min.js',
            'Markdown' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-markdown.min.js',
            'markdown' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-markdown.min.js',
            'Matlab' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-matlab.min.js',
            'matlab' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-matlab.min.js',
            'octave' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-matlab.min.js',
            'Monkey' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-monkey.min.js',
            'monkey' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-monkey.min.js',
            'Assembly' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-nasm.min.js',
            'assembly' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-nasm.min.js',
            'nasm' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-nasm.min.js',
            'Nginx' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-nginx.min.js',
            'nginx' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-nginx.min.js',
            'nginx configuration file' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-nginx.min.js',
            'Nix' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-nix.min.js',
            'nix' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-nix.min.js',
            'nixos' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-nix.min.js',
            'NSIS' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-nsis.min.js',
            'nsis' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-nsis.min.js',
            'Objective-C' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-objectivec.min.js',
            'objective-c' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-objectivec.min.js',
            'obj-c' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-objectivec.min.js',
            'objc' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-objectivec.min.js',
            'objectivec' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-objectivec.min.js',
            'OCaml' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-ocaml.min.js',
            'ocaml' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-ocaml.min.js',
            'Oz' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-oz.min.js',
            'oz' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-oz.min.js',
            'Pascal' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-pascal.min.js',
            'pascal' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-pascal.min.js',
            'Perl' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-perl.min.js',
            'perl' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-perl.min.js',
            'PHP' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-php.min.js',
            'php' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-php.min.js',
            'inc' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-php.min.js',
            'PowerShell' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-powershell.min.js',
            'powershell' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-powershell.min.js',
            'posh' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-powershell.min.js',
            'Processing' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-processing.min.js',
            'processing' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-processing.min.js',
            'Prolog' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-prolog.min.js',
            'prolog' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-prolog.min.js',
            'Puppet' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-puppet.min.js',
            'puppet' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-puppet.min.js',
            'Python' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-python.min.js',
            'python' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-python.min.js',
            'rusthon' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-python.min.js',
            'R' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-r.min.js',
            'r' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-r.min.js',
            'Rscript' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-r.min.js',
            'splus' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-r.min.js',
            'Ruby' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-ruby.min.js',
            'ruby' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-ruby.min.js',
            'jruby' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-ruby.min.js',
            'macruby' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-ruby.min.js',
            'rake' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-ruby.min.js',
            'rb' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-ruby.min.js',
            'rbx' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-ruby.min.js',
            'Rust' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-rust.min.js',
            'rust' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-rust.min.js',
            'SAS' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-sas.min.js',
            'sas' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-sas.min.js',
            'Sass' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-sass.min.js',
            'sass' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-sass.min.js',
            'Scala' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-scala.min.js',
            'scala' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-scala.min.js',
            'Scheme' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-scheme.min.js',
            'scheme' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-scheme.min.js',
            'SCSS' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-scss.min.js',
            'scss' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-scss.min.js',
            'Smalltalk' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-smalltalk.min.js',
            'smalltalk' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-smalltalk.min.js',
            'squeak' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-smalltalk.min.js',
            'Smarty' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-smarty.min.js',
            'smarty' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-smarty.min.js',
            'SQL' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-sql.min.js',
            'sql' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-sql.min.js',
            'Stylus' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-stylus.min.js',
            'stylus' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-stylus.min.js',
            'Swift' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-swift.min.js',
            'swift' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-swift.min.js',
            'Tcl' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-tcl.min.js',
            'tcl' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-tcl.min.js',
            'Textile' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-textile.min.js',
            'textile' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-textile.min.js',
            'Twig' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-twig.min.js',
            'twig' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-twig.min.js',
            'TypeScript' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-typescript.min.js',
            'typescript' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-typescript.min.js',
            'ts' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-typescript.min.js',
            'Verilog' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-verilog.min.js',
            'verilog' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-verilog.min.js',
            'VHDL' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-vhdl.min.js',
            'vhdl' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-vhdl.min.js',
            'VimL' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-vim.min.js',
            'viml' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-vim.min.js',
            'vim' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-vim.min.js',
            'nvim' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-vim.min.js',
            'YAML' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-yaml.min.js',
            'yaml' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-yaml.min.js',
            'yml' => 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-yaml.min.js',
          }
        end

        def plugins
          {
            autolinker: 'https://cdn.jsdelivr.net/prism/1.3.0/plugins/autolinker/prism-autolinker.min.js',
            autoloader: 'https://cdn.jsdelivr.net/prism/1.3.0/plugins/autoloader/prism-autoloader.min.js',
            file_highlight: 'https://cdn.jsdelivr.net/prism/1.3.0/plugins/file-highlight/prism-file-highlight.min.js',
            highlight_keywords: 'https://cdn.jsdelivr.net/prism/1.3.0/plugins/highlight-keywords/prism-highlight-keywords.min.js',
            ie8: 'https://cdn.jsdelivr.net/prism/1.3.0/plugins/ie8/prism-ie8.min.js',
            jsonp_highlight: 'https://cdn.jsdelivr.net/prism/1.3.0/plugins/jsonp-highlight/prism-jsonp-highlight.min.js',
            keep_markup: 'https://cdn.jsdelivr.net/prism/1.3.0/plugins/keep-markup/prism-keep-markup.min.js',
            line_highlight: 'https://cdn.jsdelivr.net/prism/1.3.0/plugins/line-highlight/prism-line-highlight.min.js',
            line_numbers: 'https://cdn.jsdelivr.net/prism/1.3.0/plugins/line-numbers/prism-line-numbers.min.js',
            previewer_angle: 'https://cdn.jsdelivr.net/prism/1.3.0/plugins/previewer-angle/prism-previewer-angle.min.js',
            previewer_base: 'https://cdn.jsdelivr.net/prism/1.3.0/plugins/previewer-base/prism-previewer-base.min.js',
            previewer_color: 'https://cdn.jsdelivr.net/prism/1.3.0/plugins/previewer-color/prism-previewer-color.min.js',
            previewer_easing: 'https://cdn.jsdelivr.net/prism/1.3.0/plugins/previewer-easing/prism-previewer-easing.min.js',
            previewer_gradient: 'https://cdn.jsdelivr.net/prism/1.3.0/plugins/previewer-gradient/prism-previewer-gradient.min.js',
            previewer_time: 'https://cdn.jsdelivr.net/prism/1.3.0/plugins/previewer-time/prism-previewer-time.min.js',
            remove_initial_line_feed: 'https://cdn.jsdelivr.net/prism/1.3.0/plugins/remove-initial-line-feed/prism-remove-initial-line-feed.min.js',
            show_invisibles: 'https://cdn.jsdelivr.net/prism/1.3.0/plugins/show-invisibles/prism-show-invisibles.min.js',
            show_language: 'https://cdn.jsdelivr.net/prism/1.3.0/plugins/show-language/prism-show-language.min.js',
            wpd: 'https://cdn.jsdelivr.net/prism/1.3.0/plugins/wpd/prism-wpd.min.js',
          }
        end
      end
    end
  end
end
