module Highlighter
  module Utils
    class Prism
      class << self
        def prismjs
          'https://cdn.jsdelivr.net/prism/1.3.0/prism.js'
        end

        def themes
          {
            coy: 'https://cdn.jsdelivr.net/prism/1.3.0/themes/prism-coy.css',
            dark: 'https://cdn.jsdelivr.net/prism/1.3.0/themes/prism-dark.css',
            funky: 'https://cdn.jsdelivr.net/prism/1.3.0/themes/prism-funky.css',
            okaidia: 'https://cdn.jsdelivr.net/prism/1.3.0/themes/prism-okaidia.css',
            tomorrow: 'https://cdn.jsdelivr.net/prism/1.3.0/themes/prism-tomorrow.css',
            twilight: 'https://cdn.jsdelivr.net/prism/1.3.0/themes/prism-twilight.css',
            default: 'https://cdn.jsdelivr.net/prism/1.3.0/themes/prism.css',
          }
        end

        def languages
          {
            abap: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-abap.min.js',
            actionscript: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-actionscript.min.js',
            apacheconf: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-apacheconf.min.js',
            apl: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-apl.min.js',
            applescript: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-applescript.min.js',
            asciidoc: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-asciidoc.min.js',
            aspnet: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-aspnet.min.js',
            autohotkey: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-autohotkey.min.js',
            autoit: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-autoit.min.js',
            bash: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-bash.min.js',
            basic: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-basic.min.js',
            batch: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-batch.min.js',
            bison: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-bison.min.js',
            brainfuck: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-brainfuck.min.js',
            c: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-c.min.js',
            clike: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-clike.min.js',
            coffeescript: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-coffeescript.min.js',
            core: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-core.min.js',
            cpp: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-cpp.min.js',
            crystal: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-crystal.min.js',
            csharp: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-csharp.min.js',
            css: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-css.min.js',
            d: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-d.min.js',
            dart: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-dart.min.js',
            diff: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-diff.min.js',
            docker: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-docker.min.js',
            eiffel: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-eiffel.min.js',
            elixir: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-elixir.min.js',
            erlang: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-erlang.min.js',
            fortran: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-fortran.min.js',
            fsharp: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-fsharp.min.js',
            gherkin: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-gherkin.min.js',
            git: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-git.min.js',
            glsl: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-glsl.min.js',
            go: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-go.min.js',
            groovy: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-groovy.min.js',
            haml: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-haml.min.js',
            handlebars: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-handlebars.min.js',
            haskell: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-haskell.min.js',
            haxe: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-haxe.min.js',
            http: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-http.min.js',
            icon: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-icon.min.js',
            inform7: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-inform7.min.js',
            ini: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-ini.min.js',
            j: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-j.min.js',
            jade: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-jade.min.js',
            java: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-java.min.js',
            javascript: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-javascript.min.js',
            jsx: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-jsx.min.js',
            julia: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-julia.min.js',
            keyman: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-keyman.min.js',
            kotlin: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-kotlin.min.js',
            latex: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-latex.min.js',
            less: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-less.min.js',
            lolcode: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-lolcode.min.js',
            lua: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-lua.min.js',
            makefile: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-makefile.min.js',
            markdown: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-markdown.min.js',
            markup: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-markup.min.js',
            matlab: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-matlab.min.js',
            mel: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-mel.min.js',
            mizar: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-mizar.min.js',
            monkey: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-monkey.min.js',
            nasm: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-nasm.min.js',
            nginx: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-nginx.min.js',
            nim: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-nim.min.js',
            nix: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-nix.min.js',
            nsis: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-nsis.min.js',
            objectivec: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-objectivec.min.js',
            ocaml: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-ocaml.min.js',
            oz: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-oz.min.js',
            parigp: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-parigp.min.js',
            parser: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-parser.min.js',
            pascal: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-pascal.min.js',
            perl: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-perl.min.js',
            php: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-php.min.js',
            powershell: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-powershell.min.js',
            processing: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-processing.min.js',
            prolog: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-prolog.min.js',
            puppet: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-puppet.min.js',
            pure: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-pure.min.js',
            python: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-python.min.js',
            q: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-q.min.js',
            qore: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-qore.min.js',
            r: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-r.min.js',
            rest: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-rest.min.js',
            rip: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-rip.min.js',
            roboconf: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-roboconf.min.js',
            ruby: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-ruby.min.js',
            rust: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-rust.min.js',
            sas: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-sas.min.js',
            sass: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-sass.min.js',
            scala: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-scala.min.js',
            scheme: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-scheme.min.js',
            scss: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-scss.min.js',
            smalltalk: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-smalltalk.min.js',
            smarty: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-smarty.min.js',
            sql: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-sql.min.js',
            stylus: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-stylus.min.js',
            swift: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-swift.min.js',
            tcl: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-tcl.min.js',
            textile: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-textile.min.js',
            twig: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-twig.min.js',
            typescript: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-typescript.min.js',
            verilog: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-verilog.min.js',
            vhdl: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-vhdl.min.js',
            vim: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-vim.min.js',
            wiki: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-wiki.min.js',
            yaml: 'https://cdn.jsdelivr.net/prism/1.3.0/components/prism-yaml.min.js',
          }
        end
      end
    end
  end
end
